menu:
  Docs: /guide/
  API: /api/
  Github: https://github.com/bitpay/bitcore

doc_sidebar:
  Home: 
    Get Started: index.html
    Contributing: contributing.html

  Models:
    Address: address.html
    Block: block.html
    Hierarchical: hierarchical.html
    Private Key: privatekey.html
    Public Key: publickey.html
    Script: script.html
    UnspentOutput: unspentoutput.html
    Transaction: transaction.html
  Helpers:
    Crypto: crypto.html
    ECIES: ecies.html
    Encoding: encoding.html
    Networks: networks.html
    Payment Protocol: paymentprotocol.html
    Unit: unit.html
    URI: uri.html
  Networking:
    JSON-RPC: jsonrpc.html
    Peer: peer.html
    Pool: pool.html
    Insight Explorer: insight.html

api_sidebar:
  Main: 
    Address: address.html
    Block: block.html
    BlockHeader: blockheader.html
    HDPrivateKey: hdprivatekey.html
    HDPublicKey: hdpublickey.html
    Networks: networks.html
    PrivateKey: privatekey.html
    PublicKey: publickey.html
    Unit: unit.html
    Uri: uri.html

  Crypto:
    Point: crypto/point.html

  Script:
    Script: script/script.html

  Transaction:
    Transaction: transaction/transaction.html
    UnspentOutput: transaction/unspentoutput.html
    Sig Hash: transaction/sighash.html

  Transport:
    Peer: transport/peer.html
    Pool: transport/pool.html
    RPC: transport/rpc.html
    Explorers/Insight: transport/explorers/insight.html

google_analytics: UA-24163874-2
twitter: bitpay
github: bitpay/bitcore
