menu:
  Docs: /guide/
  Github: https://github.com/bitpay/bitcore
  Forum: http://bitpaylabs.com/
  Forum: http://bitpaylabs.com/
  Playground: http://bitpay.github.io/bitcore-playground/app/


doc_sidebar:
  Home:
    Get Started: index.html
    Contributing: contributing.html

  Bitcore:
    Address: address.html
    Block: block.html
    Browser: browser.html
    Crypto: crypto.html
    Encoding: encoding.html
    HD Keys: hierarchical.html
    Networks: networks.html
    Private Key: privatekey.html
    Public Key: publickey.html
    Script: script.html
    Transaction: transaction.html
    Unit: unit.html
    Unspent Output: unspentoutput.html
    URI: uri.html

  Payment Protocol:
    Getting Started: module/payment-protocol/index.html

  Peer-to-Peer:
    Getting Started: module/p2p/index.html
    Messages: module/p2p/messages.html
    Peer: module/p2p/peer.html
    Pool: module/p2p/pool.html

  Mnemonic:
    Getting Started: module/mnemonic/index.html

  ECIES:
    Getting Started: module/ecies/index.html

  Channel:
    Getting Started: module/channel/index.html

  Explorers:
    Getting Started: module/explorers/index.html

api_sidebar:

  Bitcore:
    Address: address.html
    Block: block.html
    BlockHeader: blockheader.html
    HDPrivateKey: hdprivatekey.html
    HDPublicKey: hdpublickey.html
    Networks: networks.html
    PrivateKey: privatekey.html
    PublicKey: publickey.html
    Unit: unit.html
    Uri: uri.html
    Crypto/Point: crypto/point.html
    Script: script/script.html
    Transaction: transaction/transaction.html
    Transaction/UnspentOutput: transaction/unspentoutput.html
    Transaction/Signing: transaction/sighash.html

  Peer-to-Peer:
    Messages: module/p2p/messages.html
    Peer: module/p2p/peer.html
    Pool: module/p2p/pool.html

  Mnemonic:
    Mnemonic: module/mnemonic/mnemonic.html

  Channel:
    Consumer: module/channel/consumer.html
    Provider: module/channel/provider.html
    Transactions/Commitment: module/channel/transactions/commitment.html
    Transactions/Payment: module/channel/transactions/payment.html
    Transactions/Refund: module/channel/transactions/refund.html

  Explorers:
    Insight: module/explorers/insight.html

google_analytics: UA-24163874-2
twitter: bitpay
github: bitpay/bitcore
